services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    container_name: libr-load-balancer
    depends_on:
      - express
    environment:
      - NGINX_SERVER_NAME=localhost
      - EXPRESS_HOST_1=${EXPRESS_CONTAINER}-1
      # - EXPRESS_HOST_2=${EXPRESS_CONTAINER}-2
      # - EXPRESS_HOST_3=${EXPRESS_CONTAINER}-3
      # - EXPRESS_HOST_4=${EXPRESS_CONTAINER}-4
      # - EXPRESS_HOST_5=${EXPRESS_CONTAINER}-5
      - EXPRESS_PORT=4000
      - NGINX_MAX_BODY=100M
    ports:
      - 4000:4000
  express:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./index.js:/app/index.js
      - .env:/app/.env
      - ./uploads:/app/uploads
      - ./index.html:/app/index.html
    scale: 1
    depends_on:
      - mongodb
      - redis
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile-mongo
    container_name: ${MONGODB_CONTAINER}
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db
  redis:
    image: redis:5
    container_name: ${REDIS_CONTAINER}
    ports:
      - 6379:6379
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8082:8081"
    depends_on:
      - redis
volumes:
  mongodbdata:
